---
- name: Install redis dependencies
  ansible.builtin.dnf:
    name:
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install redis
  ansible.builtin.dnf:
    name:
      - redis
    state: present
