---
- name: Install redis
  community.general.homebrew:
    name:
      - redis
    state: present

- name: Copy redis config file into place
  ansible.builtin.copy:
    src: /opt/homebrew/etc/redis.conf
    dest: /etc/redis/redis.conf
    mode: '0755'
    owner: redis
    group: services
  become: true
  when: "OS == 'macOS'"
