---
- name: Add the user 'dask'
  ansible.builtin.user:
    name: "{{ SERVICE_USERS.DASK.username }}"
    shell: "{{ SERVICE_USERS.DASK.shell }}"
    group: "{{ SERVICE_USERS.DASK.group }}"
    groups: "{{ SERVICE_USERS.DASK.groups }}"
    uid: "{{ SERVICE_USERS.DASK.uid }}"
    append: true
  become: true
  when: "(inventory_hostname is match(INVENTORY_NAME_DASK_WORKER)) or (inventory_hostname is match(INVENTORY_NAME_DASK_PRIMARY))"

- name: Configure dask common
  ansible.builtin.include_tasks: configure.yml
  when: "(inventory_hostname is match(INVENTORY_NAME_DASK_WORKER)) or (inventory_hostname is match(INVENTORY_NAME_DASK_PRIMARY))"

- name: Setup Virtualenv
  ansible.builtin.include_tasks: venv.yml
  when: "(inventory_hostname is match(INVENTORY_NAME_DASK_WORKER)) or (inventory_hostname is match(INVENTORY_NAME_DASK_PRIMARY))"

- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: "OS == 'Ubuntu' and (inventory_hostname is match(INVENTORY_NAME_DASK_WORKER)) or (inventory_hostname is match(INVENTORY_NAME_DASK_PRIMARY))"

- name: Include macOS specific tasks
  ansible.builtin.include_tasks: macos.yml
  when: "OS == 'macOS' and (inventory_hostname is match(INVENTORY_NAME_DASK_WORKER)) or (inventory_hostname is match(INVENTORY_NAME_DASK_PRIMARY))"
