---
- name: Create dask venvs directory if it does not exist
  ansible.builtin.file:
    path: /var/lib/venvs/dask
    state: directory
    owner: dask
    group: services
    mode: '0755'
  become: true

- name: Copy requirements file
  ansible.builtin.copy:
    src: ../config/requirements.txt
    dest: /var/lib/venvs/dask/requirements.txt
    owner: dask
    group: services
    mode: '0644'
  become: true
  become_user: dask

- name: Setup dask virtualenv
  ansible.builtin.pip:
    requirements: /var/lib/venvs/dask/requirements.txt
    virtualenv: /var/lib/venvs/dask
  become: true
  become_user: dask
