---
- name: Include Linux specific tasks
  ansible.builtin.include_tasks: linux.yml
  when: "OS != 'macOS'"

- name: Include macOS specific tasks
  ansible.builtin.include_tasks: macos.yml
  when: "OS == 'macOS'"
