---
dependencies:
  - base

galaxy_info:
  role_name: desktop
  author: timkpaine
  description: Desktop / GUI Dependencies
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Raspbian
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
