---

- name: Create home directory for mount
  ansible.builtin.file:
    path: /mnt
    state: directory
    mode: '0775'
    owner: root
    group: "{{ ROOT_USER_GROUP }}"
  become: true

- name: Create home directory for mount
  ansible.builtin.file:
    path: /mnt/home
    state: directory
    mode: '0775'
    owner: root
    group: "{{ ROOT_USER_GROUP }}"
  become: true

- name: Create data directory for mount
  ansible.builtin.file:
    path: /data
    state: directory
    mode: '0775'
    owner: root
    group: "{{ ROOT_USER_GROUP }}"
  become: true

- name: Create home directory for mount
  ansible.builtin.file:
    path: /mnt/home
    state: directory
    mode: '0775'
    owner: root
    group: "{{ ROOT_USER_GROUP }}"
  become: true
