---
- name: Install the "build essential" tools
  ansible.builtin.apt:
    name: build-essential
    state: present

- name: Install "core" packages
  ansible.builtin.apt:
    name:
      - at
      - autoconf
      - automake
      - avahi-daemon
      - avahi-discover
      - avahi-utils
      - cifs-utils
      - cmake
      - cron
      - curl
      - git
      - git-lfs
      - htop
      - keyutils
      - krb5-admin-server
      - krb5-kdc
      - openjdk-11-jdk
      - libboost-dev
      - libkrb5-dev
      - libldap2-dev
      - libmnl-dev
      - libsasl2-dev
      - libxmlsec1
      - libzstd-dev
      - lm-sensors
      - lsof
      - make
      - ncat
      - ncdu
      - net-tools
      - nfs-common
      - pkg-config
      - plocate
      - smbclient
      - tar
      - telnet
      - unzip
      - uuid-dev
      - wget
      - vim
      - zip
      - zlib1g-dev
    state: present

- name: Reload service cron
  ansible.builtin.systemd:
    name: cron
    state: restarted
