---
- name: Add nginx server file for cockpit
  ansible.builtin.copy:
    dest: /etc/nginx/conf.d/{{ NGINX_COCKPIT }}-cockpit.conf
    content: |
      server {
          server_name  cockpit.{{ inventory_hostname }};
          root         /usr/share/nginx/html;

          # Load configuration files for the default server block.
          include /etc/nginx/default.d/*.conf;

          location /.well-known {
            autoindex on;
            root /opt/www-pub/;
          }

          location / {
            # TODO decide whether to lock this down or not
            # allow {{ VPN_BASE_IP }}/24;
            # deny all;
            proxy_pass http://127.0.0.1:{{ PORTS_COCKPIT }};
            proxy_redirect http://localhost:{{ PORTS_COCKPIT }} https://cockpit.{{ inventory_hostname }};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_hide_header X-Frame-Options;
            proxy_read_timeout 90;
            proxy_redirect off;
            proxy_buffers 8 32k;
            proxy_buffer_size 64k;
            proxy_set_header Origin http://$host;
            gzip off;
          }
      }
  when: "MACHINE_LOCATION == 'external' and inventory_hostname is match(INVENTORY_NAME_DESKTOP)"

- name: Add apache reverse proxy for cockpit
  ansible.builtin.copy:
    dest: /etc/httpd/conf.d/{{ NGINX_COCKPIT }}-cockpit.conf
    mode: '0644'
    content: |
      <VirtualHost *:80>
        ServerName cockpit.{{ inventory_hostname }}
        ServerAlias cockpit.{{ inventory_hostname }}

        <Location />
          Require ip {{ VPN_BASE_IP }}/24 {{ IPA_IP_ADDRESS }} 127.0.0.1
        </Location>

        Alias /.well-known/acme-challenge/ /var/www/letsencrypt/.well-known/acme-challenge/
        <Directory "/var/www/letsencrypt/.well-known/acme-challenge/">
            Options None
            AllowOverride None
            ForceType text/plain
            RedirectMatch 404 "^(?!/\.well-known/acme-challenge/[\w-]{43}$)"
        </Directory>

        SSLProxyEngine On
        SSLProxyVerify none
        SSLProxyCheckPeerCN Off
        SSLProxyCheckPeerName Off
        SSLProxyCheckPeerExpire Off

        ProxyPreserveHost On
        ProxyRequests Off

        # Proxy to your local cockpit instance
        ProxyPass /cockpit/socket ws://localhost:{{ PORTS_COCKPIT }}/cockpit/socket
        ProxyPassReverse /cockpit/socket wss://cockpit.{{ DOMAINS_IPA }}/cockpit/socket
        ProxyPass "/" http://127.0.0.1:{{ PORTS_COCKPIT }}/
        ProxyPassReverse "/" "https://cockpit.{{ DOMAINS_IPA }}/"
      </VirtualHost>
  when: "inventory_hostname is match(INVENTORY_NAME_IPA)"

- name: Add domain mappings to /etc/hosts for all possible vpn machines's netdata jobs
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {{ item.vpn_ip }} cockpit.{{ item.fqdn }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK cockpit.{{ item.username }}"
  become: true
  when: inventory_hostname is match(INVENTORY_NAME_VPN)
  loop: "{{ VPN_USERS }}"
