---
- name: Update server blocks for cockpit
  ansible.builtin.blockinfile:
    path: /etc/nginx/nginx.conf
    marker: "### {mark} ANSIBLE MANAGED BLOCK - COCKPIT"
    insertafter: "### BEGIN SERVERS"
    block: |
      server {
          server_name  cockpit.{{ inventory_hostname }};
          root         /usr/share/nginx/html;

          # Load configuration files for the default server block.
          include /etc/nginx/default.d/*.conf;

          location / {
            proxy_pass http://127.0.0.1:9090;
            proxy_redirect http://localhost:9090 https://cockpit.{{ inventory_hostname }};
            # auth_gss on;
            # auth_gss_keytab /etc/security/keytabs/sso.keytab;
            proxy_read_timeout 90;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # needed for websocket
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_buffers 8 32k;
            proxy_buffer_size 64k;

            # change scheme of "Origin" to http
            proxy_set_header Origin http://$host;

            # Pass ETag header from cockpit to clients.
            # See: https://github.com/cockpit-project/cockpit/issues/5239
            gzip off;
          }

          error_page 404 /404.html;
            location = /40x.html {
          }

          error_page 500 502 503 504 /50x.html;
            location = /50x.html {
          }
      }
