---
- name: Copy openvpn-monitor service
  ansible.builtin.copy:
    dest: /lib/systemd/system/openvpn-monitor.service
    mode: '0644'
    owner: root
    group: root
    content: |
      [Unit]
      Description=Openvpn-monitor
      Wants=network.target
      After=network.target

      [Service]
      User=vpnmon
      Type=simple
      ExecStart=/var/lib/venvs/openvpn-monitor/bin/gunicorn openvpn-monitor -b 127.0.0.1:{{ PORTS_VPN_MONITOR }}
      Restart=on-failure
      RestartSec=5s
      PrivateTmp=true

      [Install]
      WantedBy=multi-user.target
  become: true

- name: Reload daemon files
  ansible.builtin.systemd:
    daemon_reload: true
    force: true

- name: Run NGINX
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: nginx
  when: "not inventory_hostname is match('ipa*')"
