---
dependencies:
  - role: python
  - role: vpn-server
  - role: nginx

galaxy_info:
  role_name: vpn_server_monitor
  author: timkpaine
  description: Install the openvpn-monitor python package
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Raspbian
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
