---
dependencies:
  - role: base

galaxy_info:
  role_name: arrow
  author: timkpaine
  description: Install Apache Arrow
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Raspbian
    - name: Ubuntu
  galaxy_tags:
    - development
