---
dependencies:
  - role: base
  - role: hosts
  - role: firewalld

galaxy_info:
  role_name: nginx
  author: timkpaine
  description: Install custom built NGINX with support for SPNEGO
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Raspbian
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
