---
- name: Add the user 'redpanda'
  ansible.builtin.user:
    name: "{{ SERVICE_USERS.REDPANDA.username }}"
    shell: "{{ SERVICE_USERS.REDPANDA.shell }}"
    group: "{{ SERVICE_USERS.REDPANDA.group }}"
    groups: "{{ SERVICE_USERS.REDPANDA.groups }}"
    uid: "{{ SERVICE_USERS.REDPANDA.uid }}"
    append: true
  become: true
  when: "inventory_hostname is match(INVENTORY_NAME_REDPANDA_PRIMARY)"

- name: Include EL specific tasks
  ansible.builtin.include_tasks: el.yml
  when: "OS == 'EL' and inventory_hostname is match(INVENTORY_NAME_REDPANDA_PRIMARY)"

- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: "OS == 'Ubuntu' and inventory_hostname is match(INVENTORY_NAME_REDPANDA_PRIMARY)"

- name: Configure redpanda
  ansible.builtin.include_tasks: configure.yml
  when: "inventory_hostname is match(INVENTORY_NAME_REDPANDA_PRIMARY)"

- name: Run redpanda with systemd
  ansible.builtin.include_tasks: run-systemd.yml
  when: "OS != 'macOS' and inventory_hostname is match(INVENTORY_NAME_REDPANDA_PRIMARY)"
