---
- name: Include EL specific tasks
  ansible.builtin.include_tasks: el.yml
  when: "OS == 'EL' and MACHINE_LOCATION == 'external'"

- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: "OS == 'Ubuntu' and MACHINE_LOCATION == 'external'"

- name: Configure netdata
  ansible.builtin.include_tasks: configure.yml
  when: MACHINE_LOCATION == 'external'
- name: Run netdata with systemd
  ansible.builtin.include_tasks: run-systemd.yml
  when: "OS != 'macOS' and MACHINE_LOCATION == 'external'"
