---
- name: Add the user 'netdata'
  ansible.builtin.user:
    name: netdata
    shell: /bin/bash
    group: staff
    groups: services,staff
    append: true
  become: true

- name: Include EL specific tasks
  ansible.builtin.include_tasks: el.yml
  when: "OS == 'EL'"

- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: "OS == 'Ubuntu'"

- name: Configure netdata
  ansible.builtin.include_tasks: configure.yml

- name: Run netdata with systemd
  ansible.builtin.include_tasks: run-systemd.yml
  when: "OS != 'macOS'"
