---
- name: Add launch daemon for airflow scheduler
  ansible.builtin.copy:
    dest: /Library/LaunchDaemons/timkpaine.airflow-scheduler.plist
    mode: '0644'
    content: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>UserName</key>
        <string>airflow</string>
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>timkpaine.airflow-scheduler</string>
        <key>ProgramArguments</key>
        <array>
          <string>/var/lib/venvs/airflow/bin/airflow</string>
          <string>scheduler</string>
        </array>
        <key>EnvironmentVariables</key>
        <dict>
          <key>AIRFLOW_HOME</key>
          <string>/var/lib/airflow</string>
        </dict>
        <key>RunAtLoad</key>
        <true/>
        <key>StandardErrorPath</key>
        <string>/var/lib/airflow/logs/scheduler.err.log</string>
        <key>StandardOutPath</key>
        <string>/var/lib/airflow/logs/scheduler.out.log</string>
        <key>WorkingDirectory</key>
        <string>/var/lib/airflow</string>
      </dict>
      </plist>
  become: true

- name: Start airflow-scheduler with launchd
  community.general.launchd:
    name: timkpaine.airflow-scheduler
    state: restarted

- name: Add launch daemon for airflow webserver
  ansible.builtin.copy:
    dest: /Library/LaunchDaemons/timkpaine.airflow-webserver.plist
    mode: '0644'
    content: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>UserName</key>
        <string>airflow</string>
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>timkpaine.airflow-webserver</string>
        <key>ProgramArguments</key>
        <array>
          <string>/var/lib/venvs/airflow/bin/airflow</string>
          <string>webserver</string>
          <string>--pid</string>
          <string>/var/lib/airflow/webserver.pid</string>
          <string>-p</string>
          <string>{{ PORTS_AIRFLOW_WEBSERVER }}</string>
        </array>
        <key>EnvironmentVariables</key>
        <dict>
          <key>AIRFLOW_HOME</key>
          <string>/var/lib/airflow</string>
        </dict>
        <key>RunAtLoad</key>
        <true/>
        <key>StandardErrorPath</key>
        <string>/var/lib/airflow/logs/webserver.err.log</string>
        <key>StandardOutPath</key>
        <string>/var/lib/airflow/logs/webserver.out.log</string>
        <key>WorkingDirectory</key>
        <string>/var/lib/airflow</string>
      </dict>
      </plist>
  become: true

- name: Start airflow-webserver with launchd
  community.general.launchd:
    name: timkpaine.airflow-webserver
    state: restarted
