---
dependencies:
  - role: python
  - role: nginx
  - role: dask-common

galaxy_info:
  role_name: remove_dask_worker
  author: timkpaine
  description: Remove dask workers
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Raspbian
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
