---
# - name: Add reboot script to crontab
#   ansible.builtin.lineinfile:
#     path: /etc/crontab
#     line: "@reboot root /usr/local/bin/on_reboot.sh"

# - name: Copy a on_reboot.sh file into place
#   ansible.builtin.copy:
#     dest: /usr/local/bin/on_reboot.sh
#     mode: '0755'
#     content: |
#       #!/bin/bash
#       # sudo iptables -F
#   become: true
