---
- name: Install GCC 11 dependencies
  ansible.builtin.dnf:
    name:
      - centos-release-scl
    state: present

- name: Install GCC 11 from devtoolset-11
  ansible.builtin.dnf:
    name:
      - devtoolset-11-gcc
      - devtoolset-11-gcc-c++
    enablerepo: "centos-sclo-rh-testing"
    state: present
  register: installed

- name: Create helper script
  ansible.builtin.shell: |
    echo "#!/bin/bash" >> /usr/local/bin/gcc11
    echo "source /opt/rh/devtoolset-11/enable" >> /usr/local/bin/gcc11
  args:
    executable: /bin/bash
  when: "installed is succeeded"
