---
- name: Check to see if systemd assets are still around
  ansible.builtin.stat:
    path: /lib/systemd/system/dask-scheduler.service
  register: scheduler_service
  become: true

- name: Stop dask scheduler
  ansible.builtin.systemd:
    state: stopped
    enabled: false
    name: dask-scheduler
  become: true
  when: scheduler_service.stat is defined and scheduler_service.stat.exists

- name: Remove dask scheduler service
  ansible.builtin.file:
    path: /lib/systemd/system/dask-scheduler.service
    state: absent
  become: true
  when: scheduler_service.stat is defined and scheduler_service.stat.exists

- name: Reload daemon files
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
