# ---
# - name: Install nodejs repo
#   ansible.builtin.shell: |
#     curl -sL https://rpm.nodesource.com/setup_16.x | bash -
#   args:
#     executable: /bin/bash
#   vars:
#     run: true
#   when: run
#   become: true

# - name: Install nodejs package
#   ansible.builtin.dnf:
#     name:
#       - nodejs
#     state: present
#     update_cache: true
#   become: true
#   when: "OS == 'EL'"

# - name: Install yarn
#   ansible.builtin.shell: |
#     npm install -g yarn npm-run-all
#   args:
#     executable: /bin/bash
#   vars:
#     run: true
#   when: run
#   become: true
