---
dependencies:
  - role: base

galaxy_info:
  role_name: devtoolset11
  author: timkpaine
  description: Install devtoolset11 (GCC/G++ 11)
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Raspbian
    - name: Ubuntu
  galaxy_tags:
    - development
