---
dependencies:
  - role: base
  - role: nginx

galaxy_info:
  role_name: redis
  author: timkpaine
  description: Install Redis
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
