---
#############################
# Install from source on EL #
#############################
- name: Install Python dependencies
  ansible.builtin.dnf:
    name:
      - bzip2-devel
      - libffi-devel
      - ncurses-devel
      - openssl-devel
      - readline-devel
      - tcl-devel
      - tk-devel
    state: present

- name: Check if Python 3.9 installed
  ansible.builtin.stat:
    path: /usr/local/bin/python3.9
  register: already_installed

- name: Check for python 3.9.14 tarball
  ansible.builtin.stat:
    path: /opt/src/download/Python-3.9.14.tgz
  register: tgz_result
  when: "already_installed.stat is not defined or not already_installed.stat.exists"

- name: Download python 3.9.14
  ansible.builtin.get_url:
    url: https://www.python.org/ftp/python/3.9.14/Python-3.9.14.tgz
    dest: /opt/src/download
    checksum: "sha1:21419adb0b5da017a2be9271adb23e1c578e2ebf"
    mode: '0755'
  when: "(already_installed.stat is not defined or not already_installed.stat.exists) and (tgz_result.stat is not defined or not tgz_result.stat.exists)"

- name: Extract python 3.9.14
  ansible.builtin.unarchive:
    src: /opt/src/download/Python-3.9.14.tgz
    dest: /opt/src/
    remote_src: true
    creates: /opt/src/Python-3.9.14
  when: "(already_installed.stat is not defined or not already_installed.stat.exists) and (tgz_result.stat is not defined or not tgz_result.stat.exists)"

- name: Build python 3.9.14
  ansible.builtin.shell: |
    source /opt/rh/devtoolset-11/enable
    pushd /opt/src/Python-3.9.14
    ./configure --enable-optimizations
    make -j4
    touch /opt/src/Python-3.9.14/built.txt
  args:
    creates: /opt/src/Python-3.9.14/built.txt
  when: "(already_installed.stat is not defined or not already_installed.stat.exists) and (tgz_result.stat is not defined or not tgz_result.stat.exists)"

- name: Install Python 3.9.14
  ansible.builtin.shell: |
    source /opt/rh/devtoolset-11/enable
    pushd /opt/src/Python-3.9.14
    make install
  args:
    creates: /usr/local/bin/python3.14
  when: "(already_installed.stat is not defined or not already_installed.stat.exists) and (tgz_result.stat is not defined or not tgz_result.stat.exists)"
  become: true

- name: Add python to path
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: export PATH=/usr/local/bin:$PATH
  when: "(already_installed.stat is not defined or not already_installed.stat.exists)"
  become: true

###########################
