---
- name: Create download directory
  ansible.builtin.file:
    path: /opt/src/download
    state: directory
    mode: '0755'

- name: Include EL specific tasks
  ansible.builtin.include_tasks: el.yml
  when: "OS == 'EL'"

###############################
# Core Python deps / Venv dir #
###############################
- name: Install python core deps
  ansible.builtin.pip:
    name:
      - numpy
      - scipy
      - pandas
      - matplotlib
      - virtualenv
  become: true

- name: Create virtualenvs directory
  ansible.builtin.file:
    path: /var/lib/venvs
    state: directory
    mode: '0777'
    owner: root
    group: root
