---
- name: Add deadsnakes python
  ansible.builtin.apt_repository:
    validate_certs: false
    repo: 'ppa:deadsnakes/ppa'
    state: present

- name: Install python packages
  ansible.builtin.apt:
    name:
      - python3.12
      - python3.12-dev
      - python3.12-venv
    state: present
