---
- name: Add deadsnakes python
  ansible.builtin.apt_repository:
    validate_certs: no
    repo: 'ppa:deadsnakes/ppa'
    state: present

- name: Install python packages
  ansible.builtin.apt:
    name:
      - python3.11
      - python3.11-dev
      - python3.11-venv
    state: present
