---
- name: Configure dask scheduler
  ansible.builtin.include_tasks: configure.yml
  when: "inventory_hostname is match(INVENTORY_NAME_DASK_PRIMARY)"

- name: Run dask-scheduler with systemd
  ansible.builtin.include_tasks: run-systemd.yml
  when: "OS != 'macOS' and inventory_hostname is match(INVENTORY_NAME_DASK_PRIMARY)"

- name: Run dask-scheduler with launchd
  ansible.builtin.include_tasks: run-launchd.yml
  when: "OS == 'macOS' and inventory_hostname is match(INVENTORY_NAME_DASK_PRIMARY)"
