---
- name: Add launch daemon for dask-scheduler
  ansible.builtin.copy:
    dest: /Library/LaunchDaemons/timkpaine.dask-scheduler.plist
    mode: '0644'
    content: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>UserName</key>
        <string>dask</string>
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>timkpaine.dask-scheduler</string>
        <key>ProgramArguments</key>
        <array>
          <string>/var/lib/venvs/dask/bin/dask-scheduler</string>
          <string>--host</string>
          <string>0.0.0.0</string>
          <string>--port</string>
          <string>{{ PORTS_DASK_SCHEDULER }}</string>
          <string>--dashboard-address</string>
          <string>:{{ PORTS_DASK_DASHBOARD }}</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>StandardErrorPath</key>
        <string>/var/log/dask/scheduler/err.log</string>
        <key>StandardOutPath</key>
        <string>/var/log/dask/scheduler/out.log</string>
        <key>WorkingDirectory</key>
        <string>/var/lib/dask/scheduler</string>
      </dict>
      </plist>
  become: true

- name: Start dask-scheduler with launchd
  community.general.launchd:
    name: timkpaine.dask-scheduler
    state: restarted
