---
dependencies:
  - role: base
  - role: nginx

galaxy_info:
  role_name: mysql
  author: timkpaine
  description: Install MySql database
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
  galaxy_tags:
    - development
