---
dependencies: []

galaxy_info:
  role_name: users
  author: timkpaine
  description: Configure machine users and groups
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Raspbian
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
