---
- name: Configure airflow db
  ansible.builtin.include_tasks: configure.yml
  when: "inventory_hostname is match(INVENTORY_NAME_AIRFLOW_PRIMARY)"

- name: Setup and run with systemd
  ansible.builtin.include_tasks: run-systemd.yml
  when: "OS != 'macOS' and inventory_hostname is match(INVENTORY_NAME_AIRFLOW_PRIMARY)"

- name: Setup and run with launchd
  ansible.builtin.include_tasks: run-launchd.yml
  when: "OS == 'macOS' and inventory_hostname is match(INVENTORY_NAME_AIRFLOW_PRIMARY)"
