---
- name: Add launch daemon for airflow db
  ansible.builtin.copy:
    dest: /Library/LaunchDaemons/timkpaine.airflow-db.plist
    mode: '0644'
    content: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>UserName</key>
        <string>postgres</string>
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>timkpaine.airflow-db</string>
        <key>ProgramArguments</key>
        <array>
          <string>/opt/homebrew/bin/postgres</string>
          <string>-D</string>
          <string>/var/lib/pgsql/14/airflow_data</string>
          <string>-p</string>
          <string>{{ PORTS_AIRFLOW_POSTGRES }}</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>StandardErrorPath</key>
        <string>/var/log/airflow/db.err.log</string>
        <key>StandardOutPath</key>
        <string>/var/log/airflow/db.out.log</string>
        <key>WorkingDirectory</key>
        <string>/var/lib/airflow</string>
      </dict>
      </plist>
  become: true

- name: Start airflow-db with launchd
  community.general.launchd:
    name: timkpaine.airflow-db
    state: restarted
