---
dependencies:
  - role: base

galaxy_info:
  role_name: elasticsearch
  author: timkpaine
  description: Install elasticsearch
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Raspbian
  galaxy_tags:
    - development
