---
- name: Check if etcd installed
  ansible.builtin.stat:
    path: /usr/local/bin/etcd
  register: already_installed

- name: Check for tarball
  ansible.builtin.stat:
    path: /opt/src/etcd-v3.4.27-linux-amd64.tar.gz
  register: tgz_result
  when: "already_installed.stat is not defined or not already_installed.stat.exists"

- name: Download etcd
  ansible.builtin.get_url:
    url: https://github.com/etcd-io/etcd/releases/download/v3.4.27/etcd-v3.4.27-linux-amd64.tar.gz
    dest: /opt/src
    checksum: "sha1:2e7b682ab02a70502a482e4419117ff67755bfb7"
    mode: '0755'
  when: "(already_installed.stat is not defined or not already_installed.stat.exists) and (tgz_result.stat is not defined or not tgz_result.stat.exists)"

- name: Extract etcd
  ansible.builtin.unarchive:
    src: /opt/src/etcd-v3.4.27-linux-amd64.tar.gz
    dest: /opt/src/
    remote_src: true
    creates: /opt/src/etcd-v3.4.27-linux-amd64
  when: "(already_installed.stat is not defined or not already_installed.stat.exists) and (tgz_result.stat is not defined or not tgz_result.stat.exists)"

- name: Copy assets to /usr/local/
  ansible.builtin.shell: |
    cp -r /opt/src/etcd-v3.4.27-linux-amd64/etcd /usr/local/bin/
    cp -r /opt/src/etcd-v3.4.27-linux-amd64/etcdctl /usr/local/bin/
  args:
    creates: /usr/local/bin/etcd
  become: true

- name: Add /usr/local/bin to path
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: export PATH=/usr/local/bin:$PATH
  become: true
