---
- name: Create supervisor config directory
  ansible.builtin.file:
    path: /etc/supervisor
    state: directory
    mode: '0755'
    owner: supervisor
    group: services
  become: true

- name: Create supervisor working folder
  ansible.builtin.file:
    path: /var/lib/supervisor
    state: directory
    mode: '0755'
    owner: supervisor
    group: services
  become: true

- name: Create supervisor log folder
  ansible.builtin.file:
    path: /var/log/supervisor
    state: directory
    mode: '0755'
    owner: supervisor
    group: services
  become: true

- name: Create log file
  ansible.builtin.file:
    path: /var/log/supervisor/supervisord.log
    state: touch
    mode: '0755'
    owner: supervisor
    group: services
  become: true

- name: Create socket file
  ansible.builtin.file:
    path: /var/lib/supervisor/supervisor.sock
    state: touch
    mode: '0755'
    owner: supervisor
    group: services
  become: true

- name: Create pid file
  ansible.builtin.file:
    path: /var/lib/supervisor/supervisord.pid
    state: touch
    mode: '0755'
    owner: supervisor
    group: services
  become: true

- name: Setup supervisor config
  ansible.builtin.copy:
    dest: /etc/supervisor/supervisord.conf
    mode: '0755'
    owner: supervisor
    group: services
    content: |
      [supervisord]
      user=supervisor
      file=/var/lib/supervisor/supervisor.sock
      serverurl=unix:///var/lib/supervisor/supervisor.sock
      pidfile=/var/lib/supervisor/supervisord.pid
      logfile=/var/log/supervisor/supervisord.log

      [inet_http_server]
      # port = :{{ PORTS.SUPERVISOR }}
      port = 0.0.0.0:{{ PORTS.SUPERVISOR }}

      [supervisorctl]
      serverurl=http://localhost:{{ PORTS.SUPERVISOR }}

      [rpcinterface:supervisor]
      supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

      [rpcinterface:multivisor]
      supervisor.rpcinterface_factory = multivisor.rpc:make_rpc_interface
      bind=*:{{ PORTS.SUPERVISOR_MULTIVISOR }}
  become: true

- name: Configuration to run supervisor as non-root user
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/supervisor
    line: "{{ item.username }}  ALL=(ALL) NOPASSWD: /usr/bin/supervisorctl"
    create: true
  loop: "{{ USERS }}"
  become: true

# TODO keep for reference
# - name: Change socket file path in unix_http_server section
#   ansible.builtin.lineinfile:
#     dest: /etc/supervisor/supervisord.conf
#     regex: '^file='
#     line: 'file=/var/lib/supervisor/supervisor.sock'
