---
- name: Add the user 'supervisor'
  ansible.builtin.user:
    name: "{{ SERVICE_USERS.SUPERVISOR.username }}"
    shell: "{{ SERVICE_USERS.SUPERVISOR.shell }}"
    group: "{{ SERVICE_USERS.SUPERVISOR.group }}"
    groups: "{{ SERVICE_USERS.SUPERVISOR.groups }}"
    uid: "{{ SERVICE_USERS.SUPERVISOR.uid }}"
    append: true
  become: true

- name: Configure supervisor
  ansible.builtin.include_tasks: configure.yml

- name: Setup Virtualenv
  ansible.builtin.include_tasks: venv.yml

- name: Run supervisor with systemd
  ansible.builtin.include_tasks: run-systemd.yml
  when: "OS != 'macOS'"

- name: Run supervisor with launchd
  ansible.builtin.include_tasks: run-launchd.yml
  when: "OS == 'macOS'"
