---
- name: Run supervisord under systemd service
  ansible.builtin.copy:
    dest: /lib/systemd/system/supervisord.service
    mode: '0755'
    owner: root
    group: "{{ ROOT_USER_GROUP }}"
    content: |
      [Unit]
      Description=supervisord - Supervisor process control system for UNIX
      Documentation=http://supervisord.org
      After=network.target

      [Service]
      User=supervisor
      Type=forking
      ExecStart=/var/lib/venvs/supervisor/bin/supervisord -c /etc/supervisor/supervisord.conf
      ExecReload=/var/lib/venvs/supervisor/bin/supervisorctl reload
      ExecStop=/var/lib/venvs/supervisor/bin/supervisorctl shutdown

      [Install]
      WantedBy=multi-user.target
  become: true

- name: Reload daemon files
  ansible.builtin.systemd:
    daemon_reload: true
    force: true

- name: Run supervisor
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: supervisord
