---
dependencies:
  - role: python
  - role: airflow-common

galaxy_info:
  role_name: airflow_celery_worker
  author: timkpaine
  description: Run airflow celery worker
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
