---
dependencies:
  - role: base
  - role: nginx

galaxy_info:
  role_name: redpanda
  author: timkpaine
  description: Install Redpanda
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Ubuntu
  galaxy_tags:
    - development
