---
- name: Add the user 'mysql'
  ansible.builtin.user:
    name: "{{ SERVICE_USERS.MYSQL.username }}"
    shell: "{{ SERVICE_USERS.MYSQL.shell }}"
    group: "{{ SERVICE_USERS.MYSQL.group }}"
    groups: "{{ SERVICE_USERS.MYSQL.groups }}"
    uid: "{{ SERVICE_USERS.MYSQL.uid }}"
    append: true
  become: true
  when: "inventory_hostname is match(INVENTORY_NAME_MYSQL_PRIMARY)"

- name: Include EL specific tasks
  ansible.builtin.include_tasks: el.yml
  when: "OS == 'EL' and inventory_hostname is match(INVENTORY_NAME_MYSQL_PRIMARY)"

- name: Run mysql with systemd
  ansible.builtin.include_tasks: run-systemd.yml
  when: "OS != 'macOS' and inventory_hostname is match(INVENTORY_NAME_MYSQL_PRIMARY)"
