---
- name: Add the users with a bash shell, appending the user's groups
  ansible.builtin.user:
    name: "{{ item.username }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    append: true
  become: true
  loop: "{{ USERS }}"

- name: Add the service users
  ansible.builtin.user:
    name: "{{item.value.username }}"
    uid: "{{ item.value.uid }}"
    shell: "{{ item.value.shell }}"
    group: "{{ item.value.group }}"
    groups: "{{ item.value.groups }}"
    append: true
  become: true
  loop: "{{ SERVICE_USERS | dict2items }}"

- name: Add the service users
  ansible.builtin.user:
    name: "{{item.value.username }}"
    uid: "{{ item.value.uid }}"
    shell: "{{ item.value.shell }}"
    group: "{{ item.value.group }}"
    groups: "{{ item.value.groups }}"
    append: true
  become: true
  loop: "{{ SERVICE_USERS | dict2items }}"
