---
- name: Add the users with a bash shell, appending the user's groups
  ansible.builtin.user:
    name: "{{ item.username }}"
    shell: "{{ item.shell }}"
    group: staff
    groups: "{{ item.groups }}"
    append: true
  become: true
  loop: "{{ USERS }}"

- name: Add the automation users with a bash shell, appending the user's groups
  ansible.builtin.user:
    name: "{{item.value.username }}"
    uid: "{{ item.value.uid }}"
    shell: "{{ item.value.shell }}"
    group: "staff"
    groups: "{{ item.value.groups }}"
    append: true
  become: true
  loop: "{{ AUTOMATION_USERS | dict2items }}"

- name: Add the service users with a bash shell, appending the user's groups
  ansible.builtin.user:
    name: "{{item.value.username }}"
    uid: "{{ item.value.uid }}"
    shell: "{{ item.value.shell }}"
    group: "staff"
    groups: "{{ item.value.groups }}"
    append: true
  become: true
  loop: "{{ SERVICE_USERS | dict2items }}"
