---
- name: Ensure groups exist
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  become: true
  loop: "{{ GROUPS }}"

- name: Ensure all user groups exist
  ansible.builtin.group:
    name: "{{ item.username }}"
    gid: "{{ item.uid }}"
    state: present
  become: true
  loop: "{{ USERS }}"

- name: Ensure all automation user groups exist
  ansible.builtin.group:
    name: "{{item.value.username }}"
    gid: "{{ item.value.uid }}"
    state: present
  become: true
  loop: "{{ AUTOMATION_USERS | dict2items }}"

- name: Ensure all service user groups exist
  ansible.builtin.group:
    name: "{{item.value.username }}"
    gid: "{{ item.value.uid }}"
    state: present
  become: true
  loop: "{{ SERVICE_USERS | dict2items }}"

- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: linux.yml
  when: "OS == 'Ubuntu'"

- name: Include Rasbian specific tasks
  ansible.builtin.include_tasks: linux.yml
  when: "OS == 'Raspbian'"

- name: Include macOS specific tasks
  ansible.builtin.include_tasks: macos.yml
  when: "OS == 'macOS'"
