---
- name: Delete dask workers working directory
  ansible.builtin.file:
    path: /var/lib/dask/worker
    state: absent
  become: true

- name: Delete dask workers log directory
  ansible.builtin.file:
    path: /var/log/dask/worker
    state: absent
  become: true
