---
- name: Check to see if launchd assets are still around
  ansible.builtin.stat:
    path: /Library/LaunchDaemons/timkpaine.dask-worker-{{ '%d' | format(item) }}.plist
  register: plist
  loop: "{{ range(0, DASK_WORKER_COUNT, 1)  }}"
  become: true

- name: Unload airflow-db with launchd
  community.general.launchd:
    name: timkpaine.dask-worker-{{ '%d' | format(item) }}
    state: unloaded
  become: true
  when: item.stat is defined and item.stat.exists
  loop: "{{ plist.results }}"

- name: Remove launch daemon for dask worker
  ansible.builtin.file:
    path: /Library/LaunchDaemons/timkpaine.dask-worker-{{ '%d' | format(item) }}.plist
    state: absent
  become: true
  when: item.stat is defined and item.stat.exists
  loop: "{{ plist.results }}"
