---
- name: Check to see if launchd assets are still around
  ansible.builtin.stat:
    path: /Library/LaunchDaemons/timkpaine.airflow-db.plist
  register: db_plist
  become: true

- name: Unload airflow-db with launchd
  community.general.launchd:
    name: timkpaine.airflow-db
    state: unloaded
  become: true
  when: db_plist.stat is defined and db_plist.stat.exists

- name: Remove launch daemon for airflow db
  ansible.builtin.file:
    path: /Library/LaunchDaemons/timkpaine.airflow-db.plist
    state: absent
  become: true
  when: db_plist.stat is defined and db_plist.stat.exists
