---
- name: Install openvpn-monitor dependencies
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
      - geoip-database
    state: present
  when: "inventory_hostname is match('vpn*')"
