---
- name: Include generic linux tasks
  ansible.builtin.include_tasks: linux.yml
  when: "OS != 'macOS'"

- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: "OS == 'Ubuntu'"

- name: Include Raspbian specific tasks
  ansible.builtin.include_tasks: raspbian.yml
  when: "OS == 'Raspbian'"

- name: Setup and run with systemd
  ansible.builtin.include_tasks: run-systemd.yml
  when: "OS != 'macOS'"
