---
- name: Install firewalld packages
  ansible.builtin.apt:
    name:
      - firewalld
    state: present

- name: Permit traffic in default zone for http service when local
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
  when: "inventory_hostname == 'pc.local'"

- name: Permit traffic in default zone for mdns service
  ansible.posix.firewalld:
    service: mdns
    permanent: true
    state: enabled
  when: "inventory_hostname == 'pc.local'"

- name: Fixup nameserver for local resolution
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: "hosts: files mdns4_minimal dns mdns4 mdns"
  when: "inventory_hostname == 'pc.local'"
  become: true

- name: Allow local in mdns resolution
  ansible.builtin.copy:
    dest: /etc/mdns.allow
    mode: '0644'
    content: |
      .local.
      .local
  when: "inventory_hostname == 'pc.local'"
  become: true
