---
- name: Import elasticsearch rpm key
  ansible.builtin.rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add elasticsearch repository
  ansible.builtin.yum_repository:
    name: elasticsearch
    description: Elasticsearch repository for 8.x packages
    baseurl: https://artifacts.elastic.co/packages/8.x/yum
    enabled: true
    gpgcheck: true
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Install elasticsearch
  ansible.builtin.dnf:
    name:
      - elasticsearch
    state: present
