---
- name: Check if Docker installed
  ansible.builtin.shell: |
    which docker
  register: docker_install
  failed_when: false

- name: Install Docker Repo
  ansible.builtin.shell: |
    ansible.builtin.dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    executable: /bin/bash
  when: "docker_install is failed"

- name: Install Docker
  ansible.builtin.dnf:
    name:
      - docker-ce-18.03.1.ce-1.el7.centos
    state: present
  when: "docker_install is failed"

- name: Run docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  when: "OS == 'EL'"
