---
- name: Install podman
  community.general.homebrew:
    name:
      - podman
      # - podman-compose
    state: present

# - name: Alias docker to podman
#   ansible.builtin.file:
#     src: /opt/homebrew/bin/podman
#     dest: /opt/homebrew/bin/docker
#     state: link
