---
- name: Add launch daemon for dask-worker
  ansible.builtin.copy:
    dest: /Library/LaunchDaemons/timkpaine.dask-worker-{{ '%d' | format(item) }}.plist
    mode: '0644'
    content: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>UserName</key>
        <string>dask</string>
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>timkpaine.dask-worker-{{ '%d' | format(item) }}</string>
        <key>ProgramArguments</key>
        <array>
          <string>/var/lib/venvs/dask/bin/dask-worker</string>
          <string>{{ DASK_HOST }}:{{ PORTS_DASK_SCHEDULER}}</string>
          <string>--name</string>
          <string>{{ inventory_hostname }}-{{ '%d' | format(item) }}</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>StandardErrorPath</key>
        <string>/var/log/dask/worker/{{ '%d' | format(item) }}.err.log</string>
        <key>StandardOutPath</key>
        <string>/var/log/dask/worker/{{ '%d' | format(item) }}.out.log</string>
        <key>WorkingDirectory</key>
        <string>/var/lib/dask/worker/{{ '%d' | format(item) }}</string>
      </dict>
      </plist>
  become: true
  loop: "{{ range(0, DASK_WORKER_COUNT, 1)  }}"

- name: Start dask-worker with launchd
  community.general.launchd:
    name: timkpaine.dask-worker-{{ '%d' | format(item) }}
    state: restarted
  loop: "{{ range(0, DASK_WORKER_COUNT, 1)  }}"
