---
- name: Install octave
  ansible.builtin.dnf:
    name:
      - octave
      - octave-devel
    state: present

- name: Install Octave kernel for jupyter
  ansible.builtin.shell: |
    python3 -m pip install octave_kernel
  args:
    executable: /bin/bash
  vars:
    run: true
  when: run
  become: true
