---
- name: Install the 'Development tools' package group
  ansible.builtin.dnf:
    name: "@Development tools"
    state: present

- name: Install epel-release
  ansible.builtin.dnf:
    name:
      - epel-release
    state: present

- name: Install "core" packages
  ansible.builtin.dnf:
    name:
      - autoconf
      - automake
      - boost-devel
      - cmake
      - curl
      - git
      - git-lfs
      - htop
      - java-11-openjdk-devel
      - krb5-server
      - krb5-workstation
      - libmnl
      - libuuid-devel
      - lm_sensors
      - lsof
      - make
      - mlocate
      - nc
      - net-tools
      - pkgconfig
      - tar
      - telnet
      - unzip
      - wget
      - vim
      - zip
      - zlib-devel
    state: present
