---
#############
# osx steps #
#############
- name: Install "core" packages
  community.general.homebrew:
    name:
      - autoconf
      - automake
      # - boost
      - brotli
      - cairo
      - clang-format
      - cmake
      - curl
      - dos2unix
      # - flatbuffers
      - gcc
      - gh
      - git
      - git-lfs
      - hdf5
      - htop
      - jemalloc
      - jsoncpp
      - krb5
      - libev
      - libevent
      - libffi
      - libmagic
      - libpng
      - libpthread-stubs
      - librdkafka
      - libsodium
      - libuv
      - lunchy
      - lz4
      - ncurses
      - nginx
      - ninja
      - nlohmann-json
      - nmap
      - node
      - nvm
      - open-mpi
      - openjdk@11
      - openldap
      - openssl@1.1
      - pkg-config
      - podman
      - python@3.11
      - rapidjson
      - readline
      - redis
      - ruby
      - rustup-init
      - shyaml
      - snappy
      - sqlite
      - tbb
      - tcl-tk
      - telnet
      - watch
      - wget
      - zeromq
      - zstd
    state: present

- name: Install "core" packages (casks)
  community.general.homebrew_cask:
    name:
      - appcleaner
    state: present

- name: Create programs directory if it does not exist
  ansible.builtin.file:
    path: /Users/timkpaine/Developer
    state: directory
    mode: '0755'

- name: Create projects directory if it does not exist
  ansible.builtin.file:
    path: /Users/timkpaine/Developer/projects
    state: directory
    mode: '0755'
