---
- name: Run the equivalent of "apt-get update"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Update all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist

- name: Update all packages to the latest version
  ansible.builtin.apt:
    name:
      - autoconf
      - automake
      - avahi-daemon
      - avahi-utils
      - cifs-utils
      - cmake
      - cron
      - curl
      - dnsutils
      - fail2ban
      - firewalld
      - git-lfs
      - insserv
      - keyutils
      - libkrb5-dev
      - libldap2-dev
      - libleveldb-dev
      - libsasl2-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libxmlsec1-openssl
      - make
      - pkg-config
      - python3
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - samba
      - smbclient
      - systemd-resolved
      - tmux
      - wget
      - xmlsec1
      - vim
    state: present
