---
dependencies:
  - role: nginx

galaxy_info:
  role_name: nginx_routes
  author: timkpaine
  description: Setup basic routes for nginx
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Raspbian
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
