---
dependencies:
  - role: jupyter

galaxy_info:
  role_name: r_language
  author: timkpaine
  description: Install R with jupyter support
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
  galaxy_tags:
    - development
