---
- name: Add the user 'postgres'
  ansible.builtin.user:
    name: "{{ SERVICE_USERS.POSTGRES.username }}"
    shell: "{{ SERVICE_USERS.POSTGRES.shell }}"
    group: "{{ SERVICE_USERS.POSTGRES.group }}"
    groups: "{{ SERVICE_USERS.POSTGRES.groups }}"
    uid: "{{ SERVICE_USERS.POSTGRES.uid }}"
    append: true
  become: true
  when: "(inventory_hostname is match(INVENTORY_NAME_AIRFLOW_PRIMARY) or inventory_hostname is match(INVENTORY_NAME_POSTGRES_PRIMARY))"

- name: Include EL specific tasks
  ansible.builtin.include_tasks: el.yml
  when: "OS == 'EL' and (inventory_hostname is match(INVENTORY_NAME_AIRFLOW_PRIMARY) or inventory_hostname is match(INVENTORY_NAME_POSTGRES_PRIMARY))"

- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: "OS == 'Ubuntu' and (inventory_hostname is match(INVENTORY_NAME_AIRFLOW_PRIMARY) or inventory_hostname is match(INVENTORY_NAME_POSTGRES_PRIMARY))"

- name: Include Rasbian specific tasks
  ansible.builtin.include_tasks: raspbian.yml
  when: "OS == 'Raspbian' and (inventory_hostname is match(INVENTORY_NAME_AIRFLOW_PRIMARY) or inventory_hostname is match(INVENTORY_NAME_POSTGRES_PRIMARY))"

- name: Include macOS specific tasks
  ansible.builtin.include_tasks: macos.yml
  when: "OS == 'macOS' and (inventory_hostname is match(INVENTORY_NAME_AIRFLOW_PRIMARY) or inventory_hostname is match(INVENTORY_NAME_POSTGRES_PRIMARY))"

- name: Configure databases
  ansible.builtin.include_tasks: configure.yml
  when: "(inventory_hostname is match(INVENTORY_NAME_AIRFLOW_PRIMARY) or inventory_hostname is match(INVENTORY_NAME_POSTGRES_PRIMARY))"

- name: Run postgres with systemd
  ansible.builtin.include_tasks: run-systemd.yml
  when: "OS != 'macOS' and (inventory_hostname is match(INVENTORY_NAME_AIRFLOW_PRIMARY) or inventory_hostname is match(INVENTORY_NAME_POSTGRES_PRIMARY))"
