---
- name: Reload daemon files
  ansible.builtin.systemd:
    daemon_reload: true
    force: true

- name: Run postgres
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: postgresql

- name: Run postgres cluster for 'data'
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: postgresql@{{ POSTGRES_VERSION }}-data

- name: Stop postgres cluster for 'main'
  ansible.builtin.systemd:
    state: stopped
    enabled: false
    name: postgresql@{{ POSTGRES_VERSION }}-main
