---
- name: Add machines (macos-worker)
  ansible.builtin.blockinfile:
    path: /etc/supervisor/multivisor.conf
    block: |
      [supervisor:{{ item }}]
      url={{ item }}:{{ PORTS.SUPERVISOR_MULTIVISOR }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item }}"
  loop: "{{ groups['macos-worker'] }}"
  become: true
