---
- name: Configure multivisor
  ansible.builtin.include_tasks: configure.yml

- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: "OS == 'Ubuntu'"

- name: Include macOS specific tasks
  ansible.builtin.include_tasks: macos.yml
  when: "OS == 'macOS'"

- name: Run multivisor with systemd
  ansible.builtin.include_tasks: run-systemd.yml
  when: "OS != 'macOS'"

- name: Run multivisor with launchd
  ansible.builtin.include_tasks: run-launchd.yml
  when: "OS == 'macOS'"
