---
- name: Add launch daemon for supervisor
  ansible.builtin.copy:
    dest: /Library/LaunchDaemons/timkpaine.supervisor-multivisor.plist
    mode: '0644'
    content: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>UserName</key>
        <string>supervisor</string>
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>timkpaine.supervisor-multivisor</string>
        <key>ProgramArguments</key>
        <array>
          <string>/var/lib/venvs/supervisor/bin/multivisor</string>
          <string>--bind</string>
          <string>*:{{ PORTS.SUPERVISOR_MULTIVISOR_WEB }}</string>
          <string>-c</string>
          <string>/etc/supervisor/multivisor.conf</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>StandardErrorPath</key>
        <string>/var/log/supervisor/multivisor_stderr.log</string>
        <key>StandardOutPath</key>
        <string>/var/log/supervisor/multivisor_stdout.log</string>
        <key>WorkingDirectory</key>
        <string>/var/lib/supervisor/</string>
      </dict>
      </plist>
  become: true

- name: Start supervisor with launchd
  community.general.launchd:
    name: timkpaine.supervisor-multivisor
    state: reloaded

- name: Start supervisor with launchd
  community.general.launchd:
    name: timkpaine.supervisor-multivisor
    state: restarted
