---
# - name: Add the user 'dask'
#   ansible.builtin.user:
#     name: dask
#     shell: /bin/bash
#     group: staff
#     groups: services,staff
#     append: true
#   become: true

- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: "OS == 'Ubuntu'"

- name: Include macOS specific tasks
  ansible.builtin.include_tasks: macos.yml
  when: "OS == 'macOS'"

- name: Deconstruct dask common
  ansible.builtin.include_tasks: deconstruct.yml
