---
dependencies:
  - role: base
  - role: python

galaxy_info:
  role_name: airflow_common
  author: timkpaine
  description: Install prerequisites and virtualenv for airflow
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Raspbian
    - name: Ubuntu

    - name: macOS
  galaxy_tags:
    - development
