---
- name: Check if code-server installed
  ansible.builtin.stat:
    path: /usr/local/bin/code-server
  register: already_installed

- name: Create download directory
  ansible.builtin.file:
    path: /etc/code-server
    state: directory
    mode: '0755'

- name: Setup code server config
  ansible.builtin.copy:
    dest: /etc/code-server/config.yaml
    mode: '0644'
    content: |
      bind-addr: 0.0.0.0:{{ PORTS.CODESERVER }}
      auth: none
      cert: true
      cert-host: {{ inventory_hostname }}
  become: true

- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: "OS == 'Ubuntu' and (already_installed.stat is not defined or not already_installed.stat.exists)"

- name: Include macOS specific tasks
  ansible.builtin.include_tasks: macos.yml
  when: "OS == 'macOS' and (already_installed.stat is not defined or not already_installed.stat.exists)"

# NOTE: we don't start code-server, we can run it ad-hoc so its not always-on
# NOTE: we don't configure code-server with auth, locally its behind firewall
# and remotely its behind nginx SSO
