---
- name: Download code-server 4.10 .deb
  ansible.builtin.get_url:
    url: https://github.com/coder/code-server/releases/download/v4.10.0/code-server_4.10.0_amd64.deb
    dest: /opt/src/code-server_4.10.0_amd64.deb
    mode: '0755'

- name: Install code-server 4.10 .deb file
  ansible.builtin.apt:
    deb: /opt/src/code-server_4.10.0_amd64.deb

- name: Create symbolic link to bridge different installation paths
  ansible.builtin.file:
    src: /usr/bin/code-server
    dest: /usr/local/bin/code-server
    state: link
